// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartSchool.API.Data;

namespace SmartSchool.API.Migrations
{
    [DbContext(typeof(SmartContext))]
    [Migration("20210422040821_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SmartSchool.API.Models.Acoes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AcoesInfoId")
                        .HasColumnType("int");

                    b.Property<decimal>("AgressorCompra")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("AgressorVenda")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("DataPregao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NotaForca")
                        .HasColumnType("int");

                    b.Property<int>("NumNegocio")
                        .HasColumnType("int");

                    b.Property<decimal>("Ultima")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("VarD")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Volume")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AcoesInfoId");

                    b.ToTable("Acoes");
                });

            modelBuilder.Entity("SmartSchool.API.Models.AcoesInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Sigla")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("AcoesInfo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "AMBEV S/A ON",
                            Sigla = "ABEV3"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "BRASILAGRO ON NM",
                            Sigla = "AGRO3"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "ALPARGATAS PN N1",
                            Sigla = "ALPA4"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "AMBIPAR ON NM",
                            Sigla = "AMBP3"
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "ANIMA ON NM",
                            Sigla = "ANIM3"
                        },
                        new
                        {
                            Id = 6,
                            Descricao = "AREZZO CO ON NM",
                            Sigla = "ARZZ3"
                        },
                        new
                        {
                            Id = 7,
                            Descricao = "ASSAI ON NM",
                            Sigla = "ASAI3"
                        },
                        new
                        {
                            Id = 8,
                            Descricao = "AZUL PN N2",
                            Sigla = "AZUL4"
                        },
                        new
                        {
                            Id = 9,
                            Descricao = "B3 ON NM",
                            Sigla = "B3SA3"
                        },
                        new
                        {
                            Id = 10,
                            Descricao = "BRASIL ON NM",
                            Sigla = "BBAS3"
                        },
                        new
                        {
                            Id = 11,
                            Descricao = "BRADESCO PN EB N1",
                            Sigla = "BBDC4"
                        },
                        new
                        {
                            Id = 12,
                            Descricao = "BBSEGURIDADEON NM",
                            Sigla = "BBSE3"
                        },
                        new
                        {
                            Id = 13,
                            Descricao = "MINERVA ON ED NM",
                            Sigla = "BEEF3"
                        },
                        new
                        {
                            Id = 14,
                            Descricao = "BANCO INTER PN N2",
                            Sigla = "BIDI4"
                        },
                        new
                        {
                            Id = 15,
                            Descricao = "BK BRASIL ON NM",
                            Sigla = "BKBR3"
                        },
                        new
                        {
                            Id = 16,
                            Descricao = "BOA VISTA ON NM",
                            Sigla = "BOAS3"
                        },
                        new
                        {
                            Id = 17,
                            Descricao = "BTGP BANCO UNT N2",
                            Sigla = "BPAC11"
                        },
                        new
                        {
                            Id = 18,
                            Descricao = "BANCO PAN PN N1",
                            Sigla = "BPAN4"
                        },
                        new
                        {
                            Id = 19,
                            Descricao = "BRADESPAR PN N1",
                            Sigla = "BRAP4"
                        },
                        new
                        {
                            Id = 20,
                            Descricao = "PETROBRAS BRON EDR NM",
                            Sigla = "BRDT3"
                        },
                        new
                        {
                            Id = 21,
                            Descricao = "BRF SA ON NM",
                            Sigla = "BRFS3"
                        },
                        new
                        {
                            Id = 22,
                            Descricao = "BRASKEM PNA N1",
                            Sigla = "BRKM5"
                        },
                        new
                        {
                            Id = 23,
                            Descricao = "BR MALLS PARON NM",
                            Sigla = "BRML3"
                        },
                        new
                        {
                            Id = 24,
                            Descricao = "B2W DIGITAL ON NM",
                            Sigla = "BTOW3"
                        },
                        new
                        {
                            Id = 25,
                            Descricao = "CSU CARDSYSTON ED NM",
                            Sigla = "CARD3"
                        },
                        new
                        {
                            Id = 26,
                            Descricao = "MELIUZ ON NM",
                            Sigla = "CASH3"
                        },
                        new
                        {
                            Id = 27,
                            Descricao = "CCR SA ON ED NM",
                            Sigla = "CCRO3"
                        },
                        new
                        {
                            Id = 28,
                            Descricao = "CEA MODAS ON NM",
                            Sigla = "CEAB3"
                        },
                        new
                        {
                            Id = 29,
                            Descricao = "CEMIG PN N1",
                            Sigla = "CMIG4"
                        },
                        new
                        {
                            Id = 30,
                            Descricao = "CSNMINERACAOON N2",
                            Sigla = "CMIN3"
                        },
                        new
                        {
                            Id = 31,
                            Descricao = "COGNA ON ON NM",
                            Sigla = "COGN3"
                        },
                        new
                        {
                            Id = 32,
                            Descricao = "COPEL PNB N1",
                            Sigla = "CPLE6"
                        },
                        new
                        {
                            Id = 33,
                            Descricao = "CARREFOUR BRON ED NM",
                            Sigla = "CRFB3"
                        },
                        new
                        {
                            Id = 34,
                            Descricao = "COPASA ON NM",
                            Sigla = "CSMG3"
                        },
                        new
                        {
                            Id = 35,
                            Descricao = "SID NACIONALON",
                            Sigla = "CSNA3"
                        },
                        new
                        {
                            Id = 36,
                            Descricao = "CVC BRASIL ON NM",
                            Sigla = "CVCB3"
                        },
                        new
                        {
                            Id = 37,
                            Descricao = "CYRELA REALTON NM",
                            Sigla = "CYRE3"
                        },
                        new
                        {
                            Id = 38,
                            Descricao = "ECORODOVIAS ON NM",
                            Sigla = "ECOR3"
                        },
                        new
                        {
                            Id = 39,
                            Descricao = "ELETROBRAS ON N1",
                            Sigla = "ELET3"
                        },
                        new
                        {
                            Id = 40,
                            Descricao = "EMBRAER ON NM",
                            Sigla = "EMBR3"
                        },
                        new
                        {
                            Id = 41,
                            Descricao = "ENAUTA PART ON NM",
                            Sigla = "ENAT3"
                        },
                        new
                        {
                            Id = 42,
                            Descricao = "EQUATORIAL ON NM",
                            Sigla = "EQTL3"
                        },
                        new
                        {
                            Id = 43,
                            Descricao = "EVEN ON NM",
                            Sigla = "EVEN3"
                        },
                        new
                        {
                            Id = 44,
                            Descricao = "GERDAU PN N1",
                            Sigla = "GGBR4"
                        },
                        new
                        {
                            Id = 45,
                            Descricao = "GOL PN N2",
                            Sigla = "GOLL4"
                        },
                        new
                        {
                            Id = 46,
                            Descricao = "GPC PART ON",
                            Sigla = "GPCP3"
                        },
                        new
                        {
                            Id = 47,
                            Descricao = "GRENDENE ON NM",
                            Sigla = "GRND3"
                        },
                        new
                        {
                            Id = 48,
                            Descricao = "GUARARAPES ON",
                            Sigla = "GUAR3"
                        },
                        new
                        {
                            Id = 49,
                            Descricao = "CIA HERING ON NM",
                            Sigla = "HGTX3"
                        },
                        new
                        {
                            Id = 50,
                            Descricao = "HYPERA ON NM",
                            Sigla = "HYPE3"
                        },
                        new
                        {
                            Id = 51,
                            Descricao = "IGUATEMI ON NM",
                            Sigla = "IGTA3"
                        },
                        new
                        {
                            Id = 52,
                            Descricao = "INTELBRAS ON NM",
                            Sigla = "INTB3"
                        },
                        new
                        {
                            Id = 53,
                            Descricao = "ITAUUNIBANCOPN N1",
                            Sigla = "ITUB4"
                        },
                        new
                        {
                            Id = 54,
                            Descricao = "JBS ON NM",
                            Sigla = "JBSS3"
                        },
                        new
                        {
                            Id = 55,
                            Descricao = "JHSF PART ON NM",
                            Sigla = "JHSF3"
                        },
                        new
                        {
                            Id = 56,
                            Descricao = "KLABIN S/A UNT N2",
                            Sigla = "KLBN11"
                        },
                        new
                        {
                            Id = 57,
                            Descricao = "LOCAMERICA ON NM",
                            Sigla = "LCAM3"
                        },
                        new
                        {
                            Id = 58,
                            Descricao = "QUERO-QUERO ON NM",
                            Sigla = "LJQQ3"
                        },
                        new
                        {
                            Id = 59,
                            Descricao = "LOG-IN ON NM",
                            Sigla = "LOGN3"
                        },
                        new
                        {
                            Id = 60,
                            Descricao = "LOCAWEB ON NM",
                            Sigla = "LWSA3"
                        },
                        new
                        {
                            Id = 61,
                            Descricao = "M.DIASBRANCOON NM",
                            Sigla = "MDIA3"
                        },
                        new
                        {
                            Id = 62,
                            Descricao = "IMC S/A ON NM",
                            Sigla = "MEAL3"
                        },
                        new
                        {
                            Id = 63,
                            Descricao = "MAGAZ LUIZA ON NM",
                            Sigla = "MGLU3"
                        },
                        new
                        {
                            Id = 64,
                            Descricao = "MOVIDA ON NM",
                            Sigla = "MOVI3"
                        },
                        new
                        {
                            Id = 65,
                            Descricao = "MARFRIG ON ED NM",
                            Sigla = "MRFG3"
                        },
                        new
                        {
                            Id = 66,
                            Descricao = "MRV ON NM",
                            Sigla = "MRVE3"
                        },
                        new
                        {
                            Id = 67,
                            Descricao = "NEOENERGIA ON ED NM",
                            Sigla = "NEOE3"
                        },
                        new
                        {
                            Id = 68,
                            Descricao = "P.ACUCAR-CBDON NM",
                            Sigla = "PCAR3"
                        },
                        new
                        {
                            Id = 69,
                            Descricao = "PETROBRAS PN EX N2",
                            Sigla = "PETR4"
                        },
                        new
                        {
                            Id = 70,
                            Descricao = "PAGUE MENOS ON NM",
                            Sigla = "PGMN3"
                        },
                        new
                        {
                            Id = 71,
                            Descricao = "POSITIVO TECON NM",
                            Sigla = "POSI3"
                        },
                        new
                        {
                            Id = 72,
                            Descricao = "PETRORIO ON NM",
                            Sigla = "PRIO3"
                        },
                        new
                        {
                            Id = 73,
                            Descricao = "PORTOBELLO ON NM",
                            Sigla = "PTBL3"
                        },
                        new
                        {
                            Id = 74,
                            Descricao = "RUMO S.A. ON NM",
                            Sigla = "RAIL3"
                        },
                        new
                        {
                            Id = 75,
                            Descricao = "IRANI ON NM",
                            Sigla = "RANI3"
                        },
                        new
                        {
                            Id = 76,
                            Descricao = "RANDON PART PN ED N1",
                            Sigla = "RAPT4"
                        },
                        new
                        {
                            Id = 77,
                            Descricao = "REDE D OR ON NM",
                            Sigla = "RDOR3"
                        },
                        new
                        {
                            Id = 78,
                            Descricao = "LOCALIZA ON NM",
                            Sigla = "RENT3"
                        },
                        new
                        {
                            Id = 79,
                            Descricao = "INDS ROMI ON NM",
                            Sigla = "ROMI3"
                        },
                        new
                        {
                            Id = 80,
                            Descricao = "3R PETROLEUMON NM",
                            Sigla = "RRRP3"
                        },
                        new
                        {
                            Id = 81,
                            Descricao = "GRUPO SBF ON NM",
                            Sigla = "SBFG3"
                        },
                        new
                        {
                            Id = 82,
                            Descricao = "SEQUOIA LOG ON NM",
                            Sigla = "SEQL3"
                        },
                        new
                        {
                            Id = 83,
                            Descricao = "SIMPAR ON NM",
                            Sigla = "SIMH3"
                        },
                        new
                        {
                            Id = 84,
                            Descricao = "SLC AGRICOLAON NM",
                            Sigla = "SLCE3"
                        },
                        new
                        {
                            Id = 85,
                            Descricao = "SMILES ON NM",
                            Sigla = "SMLS3"
                        },
                        new
                        {
                            Id = 86,
                            Descricao = "SAO MARTINHOON NM",
                            Sigla = "SMTO3"
                        },
                        new
                        {
                            Id = 87,
                            Descricao = "SANTOS BRP ON NM",
                            Sigla = "STBP3"
                        },
                        new
                        {
                            Id = 88,
                            Descricao = "SUL AMERICA UNT N2",
                            Sigla = "SULA11"
                        },
                        new
                        {
                            Id = 89,
                            Descricao = "SUZANO S.A. ON NM",
                            Sigla = "SUZB3"
                        },
                        new
                        {
                            Id = 90,
                            Descricao = "TAURUS ARMASPN N2",
                            Sigla = "TASA4"
                        },
                        new
                        {
                            Id = 91,
                            Descricao = "TOTVS ON NM",
                            Sigla = "TOTS3"
                        },
                        new
                        {
                            Id = 92,
                            Descricao = "TRIUNFO PARTON NM",
                            Sigla = "TPIS3"
                        },
                        new
                        {
                            Id = 93,
                            Descricao = "ULTRAPAR ON NM",
                            Sigla = "UGPA3"
                        },
                        new
                        {
                            Id = 94,
                            Descricao = "USIMINAS PNA N1",
                            Sigla = "USIM5"
                        },
                        new
                        {
                            Id = 95,
                            Descricao = "VALE ON NM",
                            Sigla = "VALE3"
                        },
                        new
                        {
                            Id = 96,
                            Descricao = "VIAVAREJO ON NM",
                            Sigla = "VVAR3"
                        },
                        new
                        {
                            Id = 97,
                            Descricao = "WEG ON NM",
                            Sigla = "WEGE3"
                        },
                        new
                        {
                            Id = 98,
                            Descricao = "IBOVESPA MINI:100000120240",
                            Sigla = "WINFUT"
                        },
                        new
                        {
                            Id = 99,
                            Descricao = "YDUQS PART ON NM",
                            Sigla = "YDUQ3"
                        });
                });

            modelBuilder.Entity("SmartSchool.API.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataIni")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataNasc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Matricula")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Alunos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            DataIni = new DateTime(2021, 4, 22, 1, 8, 20, 476, DateTimeKind.Local).AddTicks(7078),
                            DataNasc = new DateTime(2005, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 1,
                            Nome = "Marta",
                            Sobrenome = "Kent",
                            Telefone = "33225555"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            DataIni = new DateTime(2021, 4, 22, 1, 8, 20, 477, DateTimeKind.Local).AddTicks(4371),
                            DataNasc = new DateTime(2005, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 2,
                            Nome = "Paula",
                            Sobrenome = "Isabela",
                            Telefone = "3354288"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            DataIni = new DateTime(2021, 4, 22, 1, 8, 20, 477, DateTimeKind.Local).AddTicks(4509),
                            DataNasc = new DateTime(2005, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 3,
                            Nome = "Laura",
                            Sobrenome = "Antonia",
                            Telefone = "55668899"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            DataIni = new DateTime(2021, 4, 22, 1, 8, 20, 477, DateTimeKind.Local).AddTicks(4522),
                            DataNasc = new DateTime(2005, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 4,
                            Nome = "Luiza",
                            Sobrenome = "Maria",
                            Telefone = "6565659"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            DataIni = new DateTime(2021, 4, 22, 1, 8, 20, 477, DateTimeKind.Local).AddTicks(4530),
                            DataNasc = new DateTime(2005, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 5,
                            Nome = "Lucas",
                            Sobrenome = "Machado",
                            Telefone = "565685415"
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            DataIni = new DateTime(2021, 4, 22, 1, 8, 20, 477, DateTimeKind.Local).AddTicks(4546),
                            DataNasc = new DateTime(2005, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 6,
                            Nome = "Pedro",
                            Sobrenome = "Alvares",
                            Telefone = "456454545"
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            DataIni = new DateTime(2021, 4, 22, 1, 8, 20, 477, DateTimeKind.Local).AddTicks(4555),
                            DataNasc = new DateTime(2005, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Matricula = 7,
                            Nome = "Paulo",
                            Sobrenome = "José",
                            Telefone = "9874512"
                        });
                });

            modelBuilder.Entity("SmartSchool.API.Models.AlunoCurso", b =>
                {
                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataIni")
                        .HasColumnType("datetime(6)");

                    b.HasKey("AlunoId", "CursoId");

                    b.HasIndex("CursoId");

                    b.ToTable("AlunosCursos");
                });

            modelBuilder.Entity("SmartSchool.API.Models.AlunoDisciplina", b =>
                {
                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataIni")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Nota")
                        .HasColumnType("int");

                    b.HasKey("AlunoId", "DisciplinaId");

                    b.HasIndex("DisciplinaId");

                    b.ToTable("AlunosDisciplinas");

                    b.HasData(
                        new
                        {
                            AlunoId = 1,
                            DisciplinaId = 2,
                            DataIni = new DateTime(2021, 4, 22, 1, 8, 20, 477, DateTimeKind.Local).AddTicks(7628)
                        },
                        new
                        {
                            AlunoId = 1,
                            DisciplinaId = 4,
                            DataIni = new DateTime(2021, 4, 22, 1, 8, 20, 478, DateTimeKind.Local).AddTicks(29)
                        },
                        new
                        {
                            AlunoId = 1,
                            DisciplinaId = 5,
                            DataIni = new DateTime(2021, 4, 22, 1, 8, 20, 478, DateTimeKind.Local).AddTicks(73)
                        },
                        new
                        {
                            AlunoId = 2,
                            DisciplinaId = 1,
                            DataIni = new DateTime(2021, 4, 22, 1, 8, 20, 478, DateTimeKind.Local).AddTicks(76)
                        },
                        new
                        {
                            AlunoId = 2,
                            DisciplinaId = 2,
                            DataIni = new DateTime(2021, 4, 22, 1, 8, 20, 478, DateTimeKind.Local).AddTicks(79)
                        },
                        new
                        {
                            AlunoId = 2,
                            DisciplinaId = 5,
                            DataIni = new DateTime(2021, 4, 22, 1, 8, 20, 478, DateTimeKind.Local).AddTicks(86)
                        },
                        new
                        {
                            AlunoId = 3,
                            DisciplinaId = 1,
                            DataIni = new DateTime(2021, 4, 22, 1, 8, 20, 478, DateTimeKind.Local).AddTicks(88)
                        },
                        new
                        {
                            AlunoId = 3,
                            DisciplinaId = 2,
                            DataIni = new DateTime(2021, 4, 22, 1, 8, 20, 478, DateTimeKind.Local).AddTicks(90)
                        },
                        new
                        {
                            AlunoId = 3,
                            DisciplinaId = 3,
                            DataIni = new DateTime(2021, 4, 22, 1, 8, 20, 478, DateTimeKind.Local).AddTicks(93)
                        },
                        new
                        {
                            AlunoId = 4,
                            DisciplinaId = 1,
                            DataIni = new DateTime(2021, 4, 22, 1, 8, 20, 478, DateTimeKind.Local).AddTicks(97)
                        },
                        new
                        {
                            AlunoId = 4,
                            DisciplinaId = 4,
                            DataIni = new DateTime(2021, 4, 22, 1, 8, 20, 478, DateTimeKind.Local).AddTicks(99)
                        },
                        new
                        {
                            AlunoId = 4,
                            DisciplinaId = 5,
                            DataIni = new DateTime(2021, 4, 22, 1, 8, 20, 478, DateTimeKind.Local).AddTicks(101)
                        },
                        new
                        {
                            AlunoId = 5,
                            DisciplinaId = 4,
                            DataIni = new DateTime(2021, 4, 22, 1, 8, 20, 478, DateTimeKind.Local).AddTicks(103)
                        },
                        new
                        {
                            AlunoId = 5,
                            DisciplinaId = 5,
                            DataIni = new DateTime(2021, 4, 22, 1, 8, 20, 478, DateTimeKind.Local).AddTicks(106)
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 1,
                            DataIni = new DateTime(2021, 4, 22, 1, 8, 20, 478, DateTimeKind.Local).AddTicks(108)
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 2,
                            DataIni = new DateTime(2021, 4, 22, 1, 8, 20, 478, DateTimeKind.Local).AddTicks(110)
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 3,
                            DataIni = new DateTime(2021, 4, 22, 1, 8, 20, 478, DateTimeKind.Local).AddTicks(113)
                        },
                        new
                        {
                            AlunoId = 6,
                            DisciplinaId = 4,
                            DataIni = new DateTime(2021, 4, 22, 1, 8, 20, 478, DateTimeKind.Local).AddTicks(117)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 1,
                            DataIni = new DateTime(2021, 4, 22, 1, 8, 20, 478, DateTimeKind.Local).AddTicks(120)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 2,
                            DataIni = new DateTime(2021, 4, 22, 1, 8, 20, 478, DateTimeKind.Local).AddTicks(122)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 3,
                            DataIni = new DateTime(2021, 4, 22, 1, 8, 20, 478, DateTimeKind.Local).AddTicks(124)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 4,
                            DataIni = new DateTime(2021, 4, 22, 1, 8, 20, 478, DateTimeKind.Local).AddTicks(126)
                        },
                        new
                        {
                            AlunoId = 7,
                            DisciplinaId = 5,
                            DataIni = new DateTime(2021, 4, 22, 1, 8, 20, 478, DateTimeKind.Local).AddTicks(128)
                        });
                });

            modelBuilder.Entity("SmartSchool.API.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Curso");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Tecnologia da Informação"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Sistemas de Informação"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Ciência da Computação"
                        });
                });

            modelBuilder.Entity("SmartSchool.API.Models.Disciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CargaHoraria")
                        .HasColumnType("int");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("PrerequisitoId")
                        .HasColumnType("int");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.HasIndex("PrerequisitoId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Disciplinas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CargaHoraria = 0,
                            CursoId = 1,
                            Nome = "Matemática",
                            ProfessorId = 1
                        },
                        new
                        {
                            Id = 2,
                            CargaHoraria = 0,
                            CursoId = 3,
                            Nome = "Matemática",
                            ProfessorId = 1
                        },
                        new
                        {
                            Id = 3,
                            CargaHoraria = 0,
                            CursoId = 3,
                            Nome = "Física",
                            ProfessorId = 2
                        },
                        new
                        {
                            Id = 4,
                            CargaHoraria = 0,
                            CursoId = 1,
                            Nome = "Português",
                            ProfessorId = 3
                        },
                        new
                        {
                            Id = 5,
                            CargaHoraria = 0,
                            CursoId = 1,
                            Nome = "Inglês",
                            ProfessorId = 4
                        },
                        new
                        {
                            Id = 6,
                            CargaHoraria = 0,
                            CursoId = 2,
                            Nome = "Inglês",
                            ProfessorId = 4
                        },
                        new
                        {
                            Id = 7,
                            CargaHoraria = 0,
                            CursoId = 3,
                            Nome = "Inglês",
                            ProfessorId = 4
                        },
                        new
                        {
                            Id = 8,
                            CargaHoraria = 0,
                            CursoId = 1,
                            Nome = "Programação",
                            ProfessorId = 5
                        },
                        new
                        {
                            Id = 9,
                            CargaHoraria = 0,
                            CursoId = 2,
                            Nome = "Programação",
                            ProfessorId = 5
                        },
                        new
                        {
                            Id = 10,
                            CargaHoraria = 0,
                            CursoId = 3,
                            Nome = "Programação",
                            ProfessorId = 5
                        });
                });

            modelBuilder.Entity("SmartSchool.API.Models.FluxoBolsa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AcoesId")
                        .HasColumnType("int");

                    b.Property<int>("AcoesInfoId")
                        .HasColumnType("int");

                    b.Property<string>("CodCorretora")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime?>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NomeCorretora")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("NumNegocio")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecoMedio")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<double>("Volume")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("AcoesId");

                    b.HasIndex("AcoesInfoId");

                    b.ToTable("FluxoBolsa");
                });

            modelBuilder.Entity("SmartSchool.API.Models.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataIni")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Registro")
                        .HasColumnType("int");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Professores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            DataIni = new DateTime(2021, 4, 22, 1, 8, 20, 463, DateTimeKind.Local).AddTicks(6079),
                            Nome = "Lauro",
                            Registro = 1,
                            Sobrenome = "Oliveira"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            DataIni = new DateTime(2021, 4, 22, 1, 8, 20, 466, DateTimeKind.Local).AddTicks(4954),
                            Nome = "Roberto",
                            Registro = 2,
                            Sobrenome = "Soares"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            DataIni = new DateTime(2021, 4, 22, 1, 8, 20, 466, DateTimeKind.Local).AddTicks(5066),
                            Nome = "Ronaldo",
                            Registro = 3,
                            Sobrenome = "Marconi"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            DataIni = new DateTime(2021, 4, 22, 1, 8, 20, 466, DateTimeKind.Local).AddTicks(5070),
                            Nome = "Rodrigo",
                            Registro = 4,
                            Sobrenome = "Carvalho"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            DataIni = new DateTime(2021, 4, 22, 1, 8, 20, 466, DateTimeKind.Local).AddTicks(5073),
                            Nome = "Alexandre",
                            Registro = 5,
                            Sobrenome = "Montanha"
                        });
                });

            modelBuilder.Entity("SmartSchool.API.Models.Acoes", b =>
                {
                    b.HasOne("SmartSchool.API.Models.AcoesInfo", "AcoesInfo")
                        .WithMany()
                        .HasForeignKey("AcoesInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartSchool.API.Models.AlunoCurso", b =>
                {
                    b.HasOne("SmartSchool.API.Models.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSchool.API.Models.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartSchool.API.Models.AlunoDisciplina", b =>
                {
                    b.HasOne("SmartSchool.API.Models.Aluno", "Aluno")
                        .WithMany("AlunosDisciplinas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSchool.API.Models.Disciplina", "Disciplina")
                        .WithMany("AlunosDisciplinas")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartSchool.API.Models.Disciplina", b =>
                {
                    b.HasOne("SmartSchool.API.Models.Curso", "Curso")
                        .WithMany("Disciplinas")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSchool.API.Models.Disciplina", "Prerequisito")
                        .WithMany()
                        .HasForeignKey("PrerequisitoId");

                    b.HasOne("SmartSchool.API.Models.Professor", "Professor")
                        .WithMany("Disciplinas")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartSchool.API.Models.FluxoBolsa", b =>
                {
                    b.HasOne("SmartSchool.API.Models.Acoes", null)
                        .WithMany("FluxoBolsas")
                        .HasForeignKey("AcoesId");

                    b.HasOne("SmartSchool.API.Models.AcoesInfo", "AcoesInfo")
                        .WithMany()
                        .HasForeignKey("AcoesInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
